// swift-tools-version: 6.0
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

// ── Platform-conditional dependencies ──────────────────────────────────
// ProjFS driver is only available on Windows
#if os(Windows)
let driverTargets: [Target] = [
    .target(
        name: "CProjFS",
        path: "Sources/Drivers/Windows/CProjFS",
        cSettings: [
            .unsafeFlags([
                "-I", "C:/Program Files (x86)/Windows Kits/10/Include/10.0.26100.0/um",
                "-I", "C:/Program Files (x86)/Windows Kits/10/Include/10.0.26100.0/shared",
            ]),
        ],
        linkerSettings: [
            .unsafeFlags([
                "-L", "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.26100.0/um/x64",
            ]),
            .linkedLibrary("ProjectedFSLib"),
            .linkedLibrary("Ole32"),
        ]
    ),
    .target(
        name: "ProjFsDriver",
        dependencies: ["SquashboxCore", "CProjFS"],
        path: "Sources/Drivers/Windows/ProjFsDriver"
    ),
]
let driverDependencies: [Target.Dependency] = ["ProjFsDriver"]
#else
let driverTargets: [Target] = []
let driverDependencies: [Target.Dependency] = []
#endif

let package = Package(
    name: "Squashbox",
    platforms: [
        .macOS(.v14),
    ],
    products: [
        .executable(name: "sqb", targets: ["sqb"]),
        .library(name: "SquashboxCore", targets: ["SquashboxCore"]),
        .library(name: "SquashFsSource", targets: ["SquashFsSource"]),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser.git", from: "1.5.0"),
    ],
    targets: [
        // ─── CORE (platform-agnostic) ───────────────────────────────────
        .target(
            name: "SquashboxCore",
            path: "Sources/SquashboxCore"
        ),

        // ─── RUST FFI BRIDGE ────────────────────────────────────────────
        //
        // squashbox_uniffiFFI: C header + modulemap generated by UniFFI.
        // Links against squashbox_uniffi.lib (Rust static library built
        // from crates/squashbox-uniffi, which wraps backhand).
        //
        .target(
            name: "squashbox_uniffiFFI",
            path: "Sources/squashbox_uniffiFFI",
            publicHeadersPath: "include",
            linkerSettings: [
                .unsafeFlags([
                    "-L", "target/release",
                ]),
                .linkedLibrary("squashbox_uniffi"),
                // Rust std dependencies on Windows
                .linkedLibrary("ws2_32"),
                .linkedLibrary("bcrypt"),
                .linkedLibrary("ntdll"),
                .linkedLibrary("userenv"),
            ]
        ),

        // ─── UNIFFI SWIFT BINDINGS ──────────────────────────────────────
        //
        // SquashboxUniFFI: Generated Swift wrapper code from UniFFI.
        // Provides SquashFsProvider, CoreError, EntryType, etc.
        // Isolated in its own module to prevent type name collisions
        // with SquashboxCore types.
        //
        .target(
            name: "SquashboxUniFFI",
            dependencies: ["squashbox_uniffiFFI"],
            path: "Sources/SquashboxUniFFI"
        ),

        // ─── SOURCES (format plugins, platform-agnostic) ────────────────
        .target(
            name: "SquashFsSource",
            dependencies: ["SquashboxCore", "SquashboxUniFFI"],
            path: "Sources/SquashFsSource"
        ),

        // ─── CLI ────────────────────────────────────────────────────────
        .executableTarget(
            name: "sqb",
            dependencies: [
                "SquashboxCore",
                "SquashFsSource",
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
            ] + driverDependencies,
            path: "Sources/sqb"
        ),

        // ─── TESTS ─────────────────────────────────────────────────────
        .testTarget(
            name: "SquashboxCoreTests",
            dependencies: ["SquashboxCore"],
            path: "Tests/SquashboxCoreTests"
        ),
        .testTarget(
            name: "SquashFsSourceTests",
            dependencies: ["SquashFsSource", "SquashboxCore"],
            path: "Tests/SquashFsSourceTests"
        ),
    ] + driverTargets
)
