// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(squashbox_uniffiFFI)
import squashbox_uniffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_squashbox_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_squashbox_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureSquashboxUniffiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * FFI-exported SquashFS provider. Wraps `squashbox_core::SquashFsProvider`.
 */
public protocol SquashFsProviderProtocol: AnyObject, Sendable {
    
    /**
     * Get attributes for a given inode.
     */
    func getAttributes(inode: UInt64) throws  -> EntryAttributes
    
    /**
     * List directory entries with pagination.
     */
    func listDirectory(inode: UInt64, cookie: UInt64) throws  -> DirEntryBatch
    
    /**
     * Look up a single entry by name within a directory.
     */
    func lookup(parentInode: UInt64, name: String) throws  -> DirEntry?
    
    /**
     * Read file content at a byte range.
     */
    func readFile(inode: UInt64, offset: UInt64, length: UInt64) throws  -> Data
    
    /**
     * Read the target of a symbolic link.
     */
    func readSymlink(inode: UInt64) throws  -> String
    
    /**
     * Resolve a relative path to an inode ID.
     */
    func resolvePath(path: String) throws  -> UInt64?
    
    /**
     * Get filesystem-level statistics.
     */
    func volumeStats() throws  -> VolumeStats
    
}
/**
 * FFI-exported SquashFS provider. Wraps `squashbox_core::SquashFsProvider`.
 */
open class SquashFsProvider: SquashFsProviderProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_squashbox_uniffi_fn_clone_squashfsprovider(self.pointer, $0) }
    }
    /**
     * Open a SquashFS image at the given path.
     */
public convenience init(imagePath: String)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_squashbox_uniffi_fn_constructor_squashfsprovider_new(
        FfiConverterString.lower(imagePath),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_squashbox_uniffi_fn_free_squashfsprovider(pointer, $0) }
    }

    

    
    /**
     * Get attributes for a given inode.
     */
open func getAttributes(inode: UInt64)throws  -> EntryAttributes  {
    return try  FfiConverterTypeEntryAttributes_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_squashbox_uniffi_fn_method_squashfsprovider_get_attributes(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(inode),$0
    )
})
}
    
    /**
     * List directory entries with pagination.
     */
open func listDirectory(inode: UInt64, cookie: UInt64)throws  -> DirEntryBatch  {
    return try  FfiConverterTypeDirEntryBatch_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_squashbox_uniffi_fn_method_squashfsprovider_list_directory(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(inode),
        FfiConverterUInt64.lower(cookie),$0
    )
})
}
    
    /**
     * Look up a single entry by name within a directory.
     */
open func lookup(parentInode: UInt64, name: String)throws  -> DirEntry?  {
    return try  FfiConverterOptionTypeDirEntry.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_squashbox_uniffi_fn_method_squashfsprovider_lookup(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(parentInode),
        FfiConverterString.lower(name),$0
    )
})
}
    
    /**
     * Read file content at a byte range.
     */
open func readFile(inode: UInt64, offset: UInt64, length: UInt64)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_squashbox_uniffi_fn_method_squashfsprovider_read_file(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(inode),
        FfiConverterUInt64.lower(offset),
        FfiConverterUInt64.lower(length),$0
    )
})
}
    
    /**
     * Read the target of a symbolic link.
     */
open func readSymlink(inode: UInt64)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_squashbox_uniffi_fn_method_squashfsprovider_read_symlink(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(inode),$0
    )
})
}
    
    /**
     * Resolve a relative path to an inode ID.
     */
open func resolvePath(path: String)throws  -> UInt64?  {
    return try  FfiConverterOptionUInt64.lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_squashbox_uniffi_fn_method_squashfsprovider_resolve_path(self.uniffiClonePointer(),
        FfiConverterString.lower(path),$0
    )
})
}
    
    /**
     * Get filesystem-level statistics.
     */
open func volumeStats()throws  -> VolumeStats  {
    return try  FfiConverterTypeVolumeStats_lift(try rustCallWithError(FfiConverterTypeCoreError_lift) {
    uniffi_squashbox_uniffi_fn_method_squashfsprovider_volume_stats(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSquashFsProvider: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SquashFsProvider

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SquashFsProvider {
        return SquashFsProvider(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SquashFsProvider) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SquashFsProvider {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SquashFsProvider, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSquashFsProvider_lift(_ pointer: UnsafeMutableRawPointer) throws -> SquashFsProvider {
    return try FfiConverterTypeSquashFsProvider.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSquashFsProvider_lower(_ value: SquashFsProvider) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSquashFsProvider.lower(value)
}




public struct DirEntry {
    public var name: String
    public var attributes: EntryAttributes

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, attributes: EntryAttributes) {
        self.name = name
        self.attributes = attributes
    }
}

#if compiler(>=6)
extension DirEntry: Sendable {}
#endif


extension DirEntry: Equatable, Hashable {
    public static func ==(lhs: DirEntry, rhs: DirEntry) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.attributes != rhs.attributes {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(attributes)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDirEntry: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DirEntry {
        return
            try DirEntry(
                name: FfiConverterString.read(from: &buf), 
                attributes: FfiConverterTypeEntryAttributes.read(from: &buf)
        )
    }

    public static func write(_ value: DirEntry, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterTypeEntryAttributes.write(value.attributes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDirEntry_lift(_ buf: RustBuffer) throws -> DirEntry {
    return try FfiConverterTypeDirEntry.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDirEntry_lower(_ value: DirEntry) -> RustBuffer {
    return FfiConverterTypeDirEntry.lower(value)
}


public struct DirEntryBatch {
    public var entries: [DirEntry]
    public var nextCookie: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(entries: [DirEntry], nextCookie: UInt64) {
        self.entries = entries
        self.nextCookie = nextCookie
    }
}

#if compiler(>=6)
extension DirEntryBatch: Sendable {}
#endif


extension DirEntryBatch: Equatable, Hashable {
    public static func ==(lhs: DirEntryBatch, rhs: DirEntryBatch) -> Bool {
        if lhs.entries != rhs.entries {
            return false
        }
        if lhs.nextCookie != rhs.nextCookie {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(entries)
        hasher.combine(nextCookie)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDirEntryBatch: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DirEntryBatch {
        return
            try DirEntryBatch(
                entries: FfiConverterSequenceTypeDirEntry.read(from: &buf), 
                nextCookie: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: DirEntryBatch, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeDirEntry.write(value.entries, into: &buf)
        FfiConverterUInt64.write(value.nextCookie, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDirEntryBatch_lift(_ buf: RustBuffer) throws -> DirEntryBatch {
    return try FfiConverterTypeDirEntryBatch.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDirEntryBatch_lower(_ value: DirEntryBatch) -> RustBuffer {
    return FfiConverterTypeDirEntryBatch.lower(value)
}


public struct EntryAttributes {
    public var inode: UInt64
    public var entryType: EntryType
    public var size: UInt64
    public var mode: UInt32
    public var uid: UInt32
    public var gid: UInt32
    public var mtimeSecs: Int64
    public var nlink: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(inode: UInt64, entryType: EntryType, size: UInt64, mode: UInt32, uid: UInt32, gid: UInt32, mtimeSecs: Int64, nlink: UInt32) {
        self.inode = inode
        self.entryType = entryType
        self.size = size
        self.mode = mode
        self.uid = uid
        self.gid = gid
        self.mtimeSecs = mtimeSecs
        self.nlink = nlink
    }
}

#if compiler(>=6)
extension EntryAttributes: Sendable {}
#endif


extension EntryAttributes: Equatable, Hashable {
    public static func ==(lhs: EntryAttributes, rhs: EntryAttributes) -> Bool {
        if lhs.inode != rhs.inode {
            return false
        }
        if lhs.entryType != rhs.entryType {
            return false
        }
        if lhs.size != rhs.size {
            return false
        }
        if lhs.mode != rhs.mode {
            return false
        }
        if lhs.uid != rhs.uid {
            return false
        }
        if lhs.gid != rhs.gid {
            return false
        }
        if lhs.mtimeSecs != rhs.mtimeSecs {
            return false
        }
        if lhs.nlink != rhs.nlink {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(inode)
        hasher.combine(entryType)
        hasher.combine(size)
        hasher.combine(mode)
        hasher.combine(uid)
        hasher.combine(gid)
        hasher.combine(mtimeSecs)
        hasher.combine(nlink)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEntryAttributes: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EntryAttributes {
        return
            try EntryAttributes(
                inode: FfiConverterUInt64.read(from: &buf), 
                entryType: FfiConverterTypeEntryType.read(from: &buf), 
                size: FfiConverterUInt64.read(from: &buf), 
                mode: FfiConverterUInt32.read(from: &buf), 
                uid: FfiConverterUInt32.read(from: &buf), 
                gid: FfiConverterUInt32.read(from: &buf), 
                mtimeSecs: FfiConverterInt64.read(from: &buf), 
                nlink: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: EntryAttributes, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.inode, into: &buf)
        FfiConverterTypeEntryType.write(value.entryType, into: &buf)
        FfiConverterUInt64.write(value.size, into: &buf)
        FfiConverterUInt32.write(value.mode, into: &buf)
        FfiConverterUInt32.write(value.uid, into: &buf)
        FfiConverterUInt32.write(value.gid, into: &buf)
        FfiConverterInt64.write(value.mtimeSecs, into: &buf)
        FfiConverterUInt32.write(value.nlink, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntryAttributes_lift(_ buf: RustBuffer) throws -> EntryAttributes {
    return try FfiConverterTypeEntryAttributes.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntryAttributes_lower(_ value: EntryAttributes) -> RustBuffer {
    return FfiConverterTypeEntryAttributes.lower(value)
}


public struct VolumeStats {
    public var totalBytes: UInt64
    public var usedBytes: UInt64
    public var totalInodes: UInt64
    public var usedInodes: UInt64
    public var blockSize: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(totalBytes: UInt64, usedBytes: UInt64, totalInodes: UInt64, usedInodes: UInt64, blockSize: UInt32) {
        self.totalBytes = totalBytes
        self.usedBytes = usedBytes
        self.totalInodes = totalInodes
        self.usedInodes = usedInodes
        self.blockSize = blockSize
    }
}

#if compiler(>=6)
extension VolumeStats: Sendable {}
#endif


extension VolumeStats: Equatable, Hashable {
    public static func ==(lhs: VolumeStats, rhs: VolumeStats) -> Bool {
        if lhs.totalBytes != rhs.totalBytes {
            return false
        }
        if lhs.usedBytes != rhs.usedBytes {
            return false
        }
        if lhs.totalInodes != rhs.totalInodes {
            return false
        }
        if lhs.usedInodes != rhs.usedInodes {
            return false
        }
        if lhs.blockSize != rhs.blockSize {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(totalBytes)
        hasher.combine(usedBytes)
        hasher.combine(totalInodes)
        hasher.combine(usedInodes)
        hasher.combine(blockSize)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVolumeStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VolumeStats {
        return
            try VolumeStats(
                totalBytes: FfiConverterUInt64.read(from: &buf), 
                usedBytes: FfiConverterUInt64.read(from: &buf), 
                totalInodes: FfiConverterUInt64.read(from: &buf), 
                usedInodes: FfiConverterUInt64.read(from: &buf), 
                blockSize: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: VolumeStats, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.totalBytes, into: &buf)
        FfiConverterUInt64.write(value.usedBytes, into: &buf)
        FfiConverterUInt64.write(value.totalInodes, into: &buf)
        FfiConverterUInt64.write(value.usedInodes, into: &buf)
        FfiConverterUInt32.write(value.blockSize, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVolumeStats_lift(_ buf: RustBuffer) throws -> VolumeStats {
    return try FfiConverterTypeVolumeStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVolumeStats_lower(_ value: VolumeStats) -> RustBuffer {
    return FfiConverterTypeVolumeStats.lower(value)
}


/**
 * FFI-safe error type matching the UDL `CoreError` enum.
 */
public enum CoreError: Swift.Error {

    
    
    case NotFound(msg: String
    )
    case NotADirectory(inode: UInt64
    )
    case NotAFile(inode: UInt64
    )
    case NotASymlink(inode: UInt64
    )
    case Io(msg: String
    )
    case SquashFs(msg: String
    )
    case NotSupported
    case ReadOnly
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreError: FfiConverterRustBuffer {
    typealias SwiftType = CoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NotFound(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .NotADirectory(
            inode: try FfiConverterUInt64.read(from: &buf)
            )
        case 3: return .NotAFile(
            inode: try FfiConverterUInt64.read(from: &buf)
            )
        case 4: return .NotASymlink(
            inode: try FfiConverterUInt64.read(from: &buf)
            )
        case 5: return .Io(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 6: return .SquashFs(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 7: return .NotSupported
        case 8: return .ReadOnly

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .NotFound(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .NotADirectory(inode):
            writeInt(&buf, Int32(2))
            FfiConverterUInt64.write(inode, into: &buf)
            
        
        case let .NotAFile(inode):
            writeInt(&buf, Int32(3))
            FfiConverterUInt64.write(inode, into: &buf)
            
        
        case let .NotASymlink(inode):
            writeInt(&buf, Int32(4))
            FfiConverterUInt64.write(inode, into: &buf)
            
        
        case let .Io(msg):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .SquashFs(msg):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(msg, into: &buf)
            
        
        case .NotSupported:
            writeInt(&buf, Int32(7))
        
        
        case .ReadOnly:
            writeInt(&buf, Int32(8))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lift(_ buf: RustBuffer) throws -> CoreError {
    return try FfiConverterTypeCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCoreError_lower(_ value: CoreError) -> RustBuffer {
    return FfiConverterTypeCoreError.lower(value)
}


extension CoreError: Equatable, Hashable {}




extension CoreError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum EntryType {
    
    case file
    case directory
    case symlink
    case blockDevice
    case charDevice
}


#if compiler(>=6)
extension EntryType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEntryType: FfiConverterRustBuffer {
    typealias SwiftType = EntryType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EntryType {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .file
        
        case 2: return .directory
        
        case 3: return .symlink
        
        case 4: return .blockDevice
        
        case 5: return .charDevice
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: EntryType, into buf: inout [UInt8]) {
        switch value {
        
        
        case .file:
            writeInt(&buf, Int32(1))
        
        
        case .directory:
            writeInt(&buf, Int32(2))
        
        
        case .symlink:
            writeInt(&buf, Int32(3))
        
        
        case .blockDevice:
            writeInt(&buf, Int32(4))
        
        
        case .charDevice:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntryType_lift(_ buf: RustBuffer) throws -> EntryType {
    return try FfiConverterTypeEntryType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEntryType_lower(_ value: EntryType) -> RustBuffer {
    return FfiConverterTypeEntryType.lower(value)
}


extension EntryType: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDirEntry: FfiConverterRustBuffer {
    typealias SwiftType = DirEntry?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDirEntry.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDirEntry.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDirEntry: FfiConverterRustBuffer {
    typealias SwiftType = [DirEntry]

    public static func write(_ value: [DirEntry], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDirEntry.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [DirEntry] {
        let len: Int32 = try readInt(&buf)
        var seq = [DirEntry]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDirEntry.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_squashbox_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_squashbox_uniffi_checksum_method_squashfsprovider_get_attributes() != 6699) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_squashbox_uniffi_checksum_method_squashfsprovider_list_directory() != 4110) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_squashbox_uniffi_checksum_method_squashfsprovider_lookup() != 26882) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_squashbox_uniffi_checksum_method_squashfsprovider_read_file() != 40002) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_squashbox_uniffi_checksum_method_squashfsprovider_read_symlink() != 65213) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_squashbox_uniffi_checksum_method_squashfsprovider_resolve_path() != 32190) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_squashbox_uniffi_checksum_method_squashfsprovider_volume_stats() != 14238) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_squashbox_uniffi_checksum_constructor_squashfsprovider_new() != 15362) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureSquashboxUniffiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all